import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import {Navbar} from "@/components/navbar/Navbar";
import {Toaster} from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col antialiased`}
      >
        <Navbar />
        <Toaster/>
        <main className="flex-1 flex">
            {children}
        </main>

      </body>
    </html>
  );
}
